### ISSUE TITLE
FT-897D communication issue: frequency may be set incorrectly

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#1065]
We've discovered an issue with FT-897D where setting the frequency to `144295000` returned a frequency of `1442950` (divided by 100) right after setting it. This has happened a couple of times, but we don't have proper debug log info from Hamlib yet, so we need more testing, but filing this here if it is a known issue. Serial speed has been lowest, 4800 bps. Otherwise CAT control has been reliable at all times.

After the frequency issue, Hamlib reported Communication timed out (error code -5) for a short time.

**Comment by mdblack98** [comment]
Need debug please...

 

    On Tuesday, June 14, 2022, 01:26:35 AM CDT, Mikael Nousiainen ***@***.***> wrote:  
 
 


We've discovered an issue with FT-897D where setting the frequency to 144295000 returned a frequency of 1442950 (divided by 100) right after setting it. This has happened a couple of times, but we don't have proper debug log info from Hamlib yet, so we need more testing, but filing this here if it is a known issue. Serial speed has been lowest, 4800 bps. Otherwise CAT control has been reliable at all times.

After the frequency issue, Hamlib reported Communication timed out (error code -5) for a short time.

**Comment by mikaelnousiainen** [comment]
I will try to get back to testing this in a couple of days.

**Comment by mikaelnousiainen** [comment]
The fix (for 100 MHz frequencies) had to be reverted, it is not correct. The issue has not surfaced after the first time. It looks like this is not an issue in Hamlib, but may have been caused by some serial port communication glitch or similar.
