### ISSUE TITLE
FLDigi not working correctly with hamlib 4.5

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#1105]
The problems with Fldigi in Linux with Hamlib 4.5 include not only the title-bar problem, but it causes Fldigi to not properly read the settings (some Fldigi settings are "lost" and must be re-selected and saved).  I'm now running Linux Mint 21 (upgraded a few days ago), and still observe the same problems.  From my previous report:
I get the strange title in the Fldigi title bar.  In addition, I noticed that some of the Fldigi settings are not read correctly, on opening the new build of Fldig, but some are read correctly.  For instance, it loses the remembered attenuation levels of the modems, thus requiring going through all those and setting them again.  Subsequent re-openings of Fldigi read all settings fine.  Looking back at my Linux Mint 20.3 system, I see that the same thing happened on it too.

Something about having Hamlib 4.5 installed in the system really messes with building Fldigi in a strange way, and now I've confirmed this on both Linux Mint 20.3 and Fedora 35, so it's going to be a ubiquitous problem.

I was hoping Dave would duplicate the problems with Linux Mint, Fedora, and MXE and be able to make some sense of the errors/problems.

Mint 21 - Hamlib 4.4 installed & Fldigi built with it:
mint@k0og-x200 ~ $ ldd /usr/local/bin/fldigi | grep hamlib
    libhamlib.so.4 => /usr/local/lib/libhamlib.so.4 (0x00007fac75061000)

Mint 21 - Hamlib 4.5 installed & Fldigi built with it (and showing the corrupted title bar):
mint@k0og-x200 ~ $ ldd /usr/local/bin/fldigi | grep hamlib
    libhamlib.so.4 => /usr/local/lib/libhamlib.so.4 (0x00007fc7cc975000)

So, the output is the same (with the parenthetical hex being different each time I do an "ldd" - even without changing anything).

73,
-Joe-

**Comment by Tyrbiter** [comment]
I have what seems to be working fldigi/flrig, these are built locally from the latest alpha versions from Dave as of right now.

I also have an up to date build of hamlib-4.5~git installed as rpms and the -devel rpm:

ldd /usr/bin/fldigi | grep hamlib

libhamlib.so.4 => /lib64/libhamlib.so.4 (0x00007fa3bf8ec000)

I also see the hex string change each time I run ldd, I suspect that it caused by address relocation for security purposes.

I have not noticed any problems with corrupted title bars.
