### ISSUE TITLE
rigmem on IC-746Pro (IC-7400) doesn't work

### ISSUE THREAD

**Issue by ra1nb0w** [Hamlib/Hamlib#125]
I am trying to use rigmem to save/change the memory of IC-746Pro on macOS 10.14. The radio is marked as stable in documentation therefore this function should work.

I am using the latest commit on master and the following OS
_macOS 10.14.6 18G87
Xcode 10.3 10G8_

Command
```
./tests/rigmem -m 346 -r /dev/cu.usbserial-14120 -a save test.csv -vvvvvv -c 0x66
```

- [rigmem_log.txt](https://github.com/Hamlib/Hamlib/files/3542301/rigmem_log.txt) contains the log of the above command
- [mem_read_bin.txt](https://github.com/Hamlib/Hamlib/files/3542322/mem_read_bin.txt) contains a binary serial dump of a program that works correctly reading all memory from the radio

At requests I can do more tests or test patches.

Thanks for the great work that you have done in these years!

**Comment by mdblack98** [comment]
Looks like you have ci-v echo turned on?
That's why the frame length error I think.
de Mike W9MDB




 

    On Monday, August 26, 2019, 01:17:28 PM CDT, rainbow <notifications@github.com> wrote:  
 
 
I am trying to use rigmem to save/change the memory of IC-746Pro on macOS 10.14. The radio is marked as stable in documentation therefore this function should work.

I am using the latest commit on master and the following OS
macOS 10.14.6 18G87
Xcode 10.3 10G8

Command
./tests/rigmem -m 346 -r /dev/cu.usbserial-14120 -a save test.csv -vvvvvv -c 0x66
   
   - rigmem_log.txt contains the log of the above command
   - mem_read.txt contains a binary serial dump of a program that works correctly reading all memory from the radio

At requests I can do more tests or test patches.

Thanks for the great work that you have done in these years!

**Comment by ra1nb0w** [comment]
I saw but for what I know the echo is part of the ci-v specification as a form of "detect collision"; see [ci-v specification](http://www.plicht.de/ekki/civ/civ-p3.html) for more information.

**Comment by mdblack98** [comment]
What's the status of this?  Working OK?
de Mike W9MDB

**Comment by ra1nb0w** [comment]
Tested with the latest commit `c9c32947` and error is still the same.

**Comment by mdblack98** [comment]
Think I have a fix for this....
Can you please contact me offline at mdblack98@yahoo.com?
Are you on Windows?
de Mike W9MDB

 

    On Thursday, January 16, 2020, 01:34:01 AM CST, rainbow <notifications@github.com> wrote:  
 
 
Tested with the latest commit c9c32947 and error is still the same.
