### ISSUE TITLE
Generating a Hamlib.pdf

### ISSUE THREAD

**Issue by gvanem** [Hamlib/Hamlib#134]
Hi (my first issue). I'm on Windows trying to build a `HamLib.pdf` using Cygwin's tool
*texi2any* and *MikTeX* with this command in `doc`.
```
/bin/texi2any --pdf hamlib.texi
```
(yes, I have created a `doc/version.texi` first). But is errors with:
```
hamlib.texi:52: @menu seen before first @node
hamlib.texi:52: perhaps your @top node should be wrapped in @ifnottex rather than @ifinfo?
```

But with this simple patch, the `HamLib.pdf` was created just fine:
```diff
--- a/doc/hamlib.texi 2019-10-10 18:09:37
+++ b/doc/hamlib.texi 2019-10-11 08:14:06
@@ -47,7 +47,6 @@

 This manual is for Ham Radio Control Libraries (Hamlib) (version @value{VERSION},
 @value{UPDATED}).
-@end ifnottex

 @menu
 * Copying and Redistribution::
@@ -59,6 +58,7 @@
 * List of Figures::
 * Concept Index::
 @end menu
+@end ifnottex
```
Does this makes sense?

**Comment by N0NB** [comment]
That patch does take a couple of blank pages out of the PDF.  
Interesting that texi2pdf works OK.
It doesn't affect the html or info file.
Moving it down a bit further also gets rid of 2 more blank pages.
I'll submit the patch to include this and pretty it up a bit too.
de Mike W9MDB


 

    On Friday, October 11, 2019, 03:27:06 AM CDT, Gisle Vanem <notifications@github.com> wrote:  
 
 
Hi (my first issue). I'm on Windows trying to build a HamLib.pdf using Cygwin's tool
texi2any and MikTeX with this command in doc.
sh /bin/texi2any --pdf hamlib.texi

(yes, I have created a doc/version.texi first). But is errors with:
hamlib.texi:52: @menu seen before first @node
hamlib.texi:52: perhaps your @top node should be wrapped in @ifnottex rather than @ifinfo?

But with this simple patch, the HamLib.pdf was created just fine:
--- a/doc/hamlib.texi 2019-10-10 18:09:37
+++ b/doc/hamlib.texi 2019-10-11 08:14:06
@@ -47,7 +47,6 @@

 This manual is for Ham Radio Control Libraries (Hamlib) (version @value{VERSION},
 @value{UPDATED}).
-@end ifnottex

 @menu
 * Copying and Redistribution::
@@ -59,6 +58,7 @@
 * List of Figures::
 * Concept Index::
 @end menu
+@end ifnottex
Does this makes sense?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by mdblack98** [comment]
Fixed
