### ISSUE TITLE
Rigctl set_ant and get_ant may require VFO

### ISSUE THREAD

**Issue by mikaelnousiainen** [Hamlib/Hamlib#1399]
Both `set_ant` and `get_ant` may need VFO, because some more advanced rigs have targetable antenna selection.

Please see my comment in this commit: https://github.com/Hamlib/Hamlib/commit/64d6cd4af270bd2e94968eb6df5c34202b0763a4

**Comment by mdblack98** [comment]
Which rigs would that be?
I would need to fix them too.

Mike W9MDB








On Tuesday, October 10, 2023 at 09:33:26 AM CDT, Mikael Nousiainen ***@***.***> wrote: 







Both set_ant and get_ant may need VFO, because some more advanced rigs have targetable antenna selection.

Please see my comment in this commit: 64d6cd4

**Comment by mdblack98** [comment]
Or better said...do you know of any other rigs that need this?








On Tuesday, October 10, 2023 at 10:41:10 AM CDT, Michael Black ***@***.***> wrote: 






Which rigs would that be? 
I would need to fix them too. 

Mike W9MDB 








On Tuesday, October 10, 2023 at 09:33:26 AM CDT, Mikael Nousiainen ***@***.***> wrote: 







Both set_ant and get_ant may need VFO, because some more advanced rigs have targetable antenna selection. 

Please see my comment in this commit: 64d6cd4

**Comment by mikaelnousiainen** [comment]
At least FTDX5000 and FTDX9000 seem to allow this in addition to the newer FTDX101. Didn't check others yet, but just wanted to fix the issue in the commands to allow targetable antenna selection. Thanks!
