### ISSUE TITLE
IC-7100 & rigctl - bad CI-V address

### ISSUE THREAD

**Issue by malcolmh** [Hamlib/Hamlib#169]
Running rigctl for IC7100 (rig 341), the ci-v address output is not the value in priv_caps. If I use the -c switch with the correct value, that works OK. If I edit the value in ic7100.c, it still outputs the same wrong value. FYI, 0x88 is the correct value - 0x34 is the value that is output.

My fork is synced with the latest mdblack fork.

**Comment by N0NB** [comment]
That's because the IC7100 is rig 370The IC-R7000 is 341
   341  Icom                   IC-R7100                0.19.0          Untested   370  Icom                   IC-7100                 0.19.0          Untested




 

    On Monday, January 6, 2020, 02:10:58 PM CST, Malcolm Herring <notifications@github.com> wrote:  
 
 
Running rigctl for IC7100 (rig 341), the ci-v address output is not the value in priv_caps. If I use the -c switch with the correct value, that works OK. If I edit the value in ic7100.c, it still outputs the same wrong value. FYI, 0x88 is the correct value - 0x34 is the value that is output.

My fork is synced with the latest mdblack fork.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by malcolmh** [comment]
My Bad!
