### ISSUE TITLE
Rig failure with Yaesu FT-900

### ISSUE THREAD

**Issue by Zazzmatazz** [Hamlib/Hamlib#176]
Good afternoon;

I am receiving an error when attempting to configure a Yaesu FT-900 in WSJT-X.

My settings are as follows:

- Baud: 4800
- Data Bits: 8
- Stop Bits: Two
- Handshake: None
- PTT Method: CAT
- Mode: USB
- Split Operation: None
- Polling Interval: 1s

The error I am receiving is:
"Rig failure.  Hamlib error: Invalid parameter while testing getting current VFO"

I am seeing the "CAT" indicator appearing on screen, which at least indicates that the radio is seeing the DTR signal, but I don't have any other information beyond that.

I attempted to run `rigctl` with the FT-900 (radio ID 113) and received this:
```
> .\rigctl -m 113 -r COM11 -s 4800 f m t
get_freq: error = Invalid parameter
get_mode: error = Communication timed out
0
```

Note that during the first part (i.e. "get_freq"), the "CAT" indicator on the FT-900 lit up, suggesting that it recognized a command.

**Comment by N0NB** [comment]
What version of WSJT-X?
Is your rig in some non-standard mode?  Try setting the rig to USB before starting WSJT-X.
de Mike W9MDB

 

    On Friday, January 17, 2020, 04:34:39 PM CST, Patrick Mathis <notifications@github.com> wrote:  
 
 
Good afternoon;

I am receiving an error when attempting to configure a Yaesu FT-900 in WSJT-X.

My settings are as follows:
   
   - Baud: 4800
   - Data Bits: 8
   - Stop Bits: Two
   - Handshake: None
   - PTT Method: CAT
   - Mode: USB
   - Split Operation: None
   - Polling Interval: 1s

The error I am receiving is:
"Rig failure. Hamlib error: Invalid parameter while testing getting current VFO"

I am seeing the "CAT" indicator appearing on screen, which at least indicates that the radio is seeing the DTR signal, but I don't have any other information beyond that. I will attempt to connect a serial terminal between the application and the radio in order to examine the communications in more detail.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by Zazzmatazz** [comment]
Hello @N0NB,

The radio is currently in VFO-A, frequency dial is locked and frequency is currently on 18.100 MHz USB.

**Comment by N0NB** [comment]
Unlock the frequency dial.  That may be the problem.



 

    On Friday, January 17, 2020, 04:59:59 PM CST, Patrick Mathis <notifications@github.com> wrote:  
 
 
Hello @N0NB,

The radio is currently in VFO-A, frequency dial is locked and frequency is currently on 18.100 MHz USB.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by Zazzmatazz** [comment]
There is no change sadly, same exact error.

**Comment by N0NB** [comment]
Contact me off list at mdblack98@yahoo.com
Mike

 

    On Friday, January 17, 2020, 05:07:21 PM CST, Patrick Mathis <notifications@github.com> wrote:  
 
 
There is no change sadly, same exact error.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe._______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer
