### ISSUE TITLE
K3/KX3 w TX; timeout

### ISSUE THREAD

**Issue by hlnurse** [Hamlib/Hamlib#198]
The normal rigctl TX/RX commands (T 1, T 0) work as they should.  However, w TX; and w RX; wait for a response from the radio for 2.5 seconds before timing out.  

--Howard W6HN

Rig command: w RX;
rigctl_parse: debug1
rigctl_parse: debug2
rigctl_parse: debug2a
rigctl_parse: debug5
rigctl_parse: debug10
rigctl_send_cmd: called
rigctl_send_cmd: backend_num=0
rigctl_send_cmd: arg1=RX;
rigctl_send_cmd: we're netrigctl#2
rigctl_send_cmd: cmd=w RX;
, len=6
serial_flush called
serial_flush: tcflush
rigctl_send_cmd: rigport=3, bufcmd=w RX;
, cmd_len=6
write_block called
write_block(): TX 6 bytes
0000    77 20 52 58 3b 0a                                   w RX;.          
rigctl_send_cmd: debug Cmd
read_string called
read_string(): Timed out 2.502566 seconds after 0 chars
rigctl_send_cmd: read_string error Communication timed out
Reply:

**Comment by mdblack98** [comment]
That because the TX and RX commands don't return anything.  They are one-way commands.
If you want to get some response just take and ID; on there
Rig command: w TX;ID;
rigctl_parse: debug1
rigctl_parse: debug2
rigctl_parse: debug2a
rigctl_parse: debug5
rigctl_parse: debug10
rigctl_send_cmd: called
rigctl_send_cmd: backend_num=0
rigctl_send_cmd: arg1=TX;ID;
rigctl_send_cmd: we're netrigctl#2
rigctl_send_cmd: cmd=w TX;ID;
, len=9
serial_flush called
serial_flush: tcflush
rigctl_send_cmd: rigport=240, bufcmd=w TX;ID;
, cmd_len=9
write_block called
write_block(): TX 9 bytes
0000    77 20 54 58 3b 49 44 3b 0a                          w TX;ID;.
rigctl_send_cmd: debug Cmd
Reply:read_string called
read_string(): RX 7 characters
0000    49 44 39 30 30 3b 0a                                ID900;.
ID900;
