### ISSUE TITLE
TS-480 set_powerstat

### ISSUE THREAD

**Issue by hlnurse** [Hamlib/Hamlib#205]
Power on using set_powerstat for the TS-480 appears to be broken.  The TS-480 has two power off modes, one (PS3;) where the cpu sleeps and the other (PS0;) where the cpu is active.   Shouldn't the TS-480 attempt power on as part of the init?  

Log below.

Thanks!

--Howard W6HN

pi@rigpi:~/Downloads/Hamlib-master $ rigctl -m 2028 -r /dev/ttyUSB0 -vvvvv
rigctl, Hamlib 4.0~git
Report bugs to <hamlib-developer@lists.sourceforge.net>

rig_init called
initrigs4_kenwood called
rig_register called
rig_register: rig_register (2013)
rig_register called
rig_register: rig_register (2001)
rig_register called
rig_register: rig_register (2025)
rig_register called
rig_register: rig_register (2003)
rig_register called
rig_register: rig_register (2004)
rig_register called
rig_register: rig_register (2016)
rig_register called
rig_register: rig_register (2024)
rig_register called
rig_register: rig_register (2005)
rig_register called
rig_register: rig_register (2007)
rig_register called
rig_register: rig_register (2009)
rig_register called
rig_register: rig_register (2010)
rig_register called
rig_register: rig_register (2022)
rig_register called
rig_register: rig_register (2014)
rig_register called
rig_register: rig_register (2030)
rig_register called
rig_register: rig_register (2021)
rig_register called
rig_register: rig_register (2029)
rig_register called
rig_register: rig_register (2043)
rig_register called
rig_register: rig_register (2044)
rig_register called
rig_register: rig_register (2045)
rig_register called
rig_register: rig_register (2038)
rig_register called
rig_register: rig_register (2002)
rig_register called
rig_register: rig_register (2011)
rig_register called
rig_register: rig_register (2006)
rig_register called
rig_register: rig_register (2008)
rig_register called
rig_register: rig_register (2015)
rig_register called
rig_register: rig_register (2026)
rig_register called
rig_register: rig_register (2017)
rig_register called
rig_register: rig_register (2033)
rig_register called
rig_register: rig_register (2042)
rig_register called
rig_register: rig_register (2020)
rig_register called
rig_register: rig_register (2023)
rig_register called
rig_register: rig_register (2027)
rig_register called
rig_register: rig_register (2034)
rig_register called
rig_register: rig_register (2031)
rig_register called
rig_register: rig_register (2039)
rig_register called
rig_register: rig_register (2037)
rig_register called
rig_register: rig_register (2028)
rig_register called
rig_register: rig_register (2019)
rig_register called
rig_register: rig_register (2032)
rig_register called
rig_register: rig_register (2036)
rig_register called
rig_register: rig_register (2040)
rig_register called
rig_register: rig_register (2041)
kenwood_init called, version 1.5
kenwood_init: if_len = 37
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
serial_flush: tcflush
rig_get_vfo called
kenwood_get_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): RX 1 characters
0000    00                                                  .               
kenwood_transaction: wrong reply  for command IF
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200264 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200257 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000    49 46 3b                                            IF;             
read_string called
read_string(): Timed out 0.200258 seconds after 0 chars
rig_set_parm called
Opened rig model 2028, 'TS-480'
Backend version: 1.5.5, Status: Untested

Rig command: \set_powerstat 1
rigctl_parse: debug1
rigctl_parse: debug3
rigctl_parse: debug4
rigctl_parse: debug5
rigctl_parse: debug10
rig_set_powerstat called
kenwood_transaction called
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): RX 1 characters
0000    00                                                  .               
kenwood_transaction: wrong reply  for command verification ID
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200266 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200271 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000    50 53 31 3b                                         PS1;            
write_block called
write_block(): TX 3 bytes
0000    49 44 3b                                            ID;             
read_string called
read_string(): Timed out 0.200274 seconds after 0 chars
kenwood_set_powerstat called status=1
kenwood_set_powerstat: timeout waiting for powerup, try 1
set_powerstat: error = Communication timed out

**Comment by N0NB** [comment]
According to the TS-480 document I have PS9; is the CPU sleep.
So if you send ";;;;PS1;" does it wake up?
Using the "w" command from rigctl?
w ;;;;PS1;

 

    On Tuesday, March 3, 2020, 05:15:49 PM CST, hlnurse <notifications@github.com> wrote:  
 
 
Power on using set_powerstat for the TS-480 appears to be broken. The TS-480 has two power off modes, one (PS3;) where the cpu sleeps and the other (PS0;) where the cpu is active. Shouldn't the TS-480 attempt power on as part of the init?

Log below.

Thanks!

--Howard W6HN

pi@rigpi:
git
Report bugs to hamlib-developer@lists.sourceforge.net

rig_init called
initrigs4_kenwood called
rig_register called
rig_register: rig_register (2013)
rig_register called
rig_register: rig_register (2001)
rig_register called
rig_register: rig_register (2025)
rig_register called
rig_register: rig_register (2003)
rig_register called
rig_register: rig_register (2004)
rig_register called
rig_register: rig_register (2016)
rig_register called
rig_register: rig_register (2024)
rig_register called
rig_register: rig_register (2005)
rig_register called
rig_register: rig_register (2007)
rig_register called
rig_register: rig_register (2009)
rig_register called
rig_register: rig_register (2010)
rig_register called
rig_register: rig_register (2022)
rig_register called
rig_register: rig_register (2014)
rig_register called
rig_register: rig_register (2030)
rig_register called
rig_register: rig_register (2021)
rig_register called
rig_register: rig_register (2029)
rig_register called
rig_register: rig_register (2043)
rig_register called
rig_register: rig_register (2044)
rig_register called
rig_register: rig_register (2045)
rig_register called
rig_register: rig_register (2038)
rig_register called
rig_register: rig_register (2002)
rig_register called
rig_register: rig_register (2011)
rig_register called
rig_register: rig_register (2006)
rig_register called
rig_register: rig_register (2008)
rig_register called
rig_register: rig_register (2015)
rig_register called
rig_register: rig_register (2026)
rig_register called
rig_register: rig_register (2017)
rig_register called
rig_register: rig_register (2033)
rig_register called
rig_register: rig_register (2042)
rig_register called
rig_register: rig_register (2020)
rig_register called
rig_register: rig_register (2023)
rig_register called
rig_register: rig_register (2027)
rig_register called
rig_register: rig_register (2034)
rig_register called
rig_register: rig_register (2031)
rig_register called
rig_register: rig_register (2039)
rig_register called
rig_register: rig_register (2037)
rig_register called
rig_register: rig_register (2028)
rig_register called
rig_register: rig_register (2019)
rig_register called
rig_register: rig_register (2032)
rig_register called
rig_register: rig_register (2036)
rig_register called
rig_register: rig_register (2040)
rig_register called
rig_register: rig_register (2041)
kenwood_init called, version 1.5
kenwood_init: if_len = 37
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
serial_flush: tcflush
rig_get_vfo called
kenwood_get_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): RX 1 characters
0000 00 .
kenwood_transaction: wrong reply for command IF
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200264 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200257 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200258 seconds after 0 chars
rig_set_parm called
Opened rig model 2028, 'TS-480'
Backend version: 1.5.5, Status: Untested

Rig command: \set_powerstat 1
rigctl_parse: debug1
rigctl_parse: debug3
rigctl_parse: debug4
rigctl_parse: debug5
rigctl_parse: debug10
rig_set_powerstat called
kenwood_transaction called
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): RX 1 characters
0000 00 .
kenwood_transaction: wrong reply for command verification ID
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200266 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200271 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200274 seconds after 0 chars
kenwood_set_powerstat called status=1
kenwood_set_powerstat: timeout waiting for powerup, try 1
set_powerstat: error = Communication timed out

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by mdblack98** [comment]
Try my fork....I just added the kenwood_open to the TS480 and change the PS1 command to wake up a sleeping CPU too (hopefully).
https://github.com/mdblack98/Hamlib

de Mike W9MDB

 

    On Tuesday, March 3, 2020, 05:22:09 PM CST, Nate Bargmann <notifications@github.com> wrote:  
 
 According to the TS-480 document I have PS9; is the CPU sleep.
So if you send ";;;;PS1;" does it wake up?
Using the "w" command from rigctl?
w ;;;;PS1;

 

 On Tuesday, March 3, 2020, 05:15:49 PM CST, hlnurse <notifications@github.com> wrote: 
 
 
Power on using set_powerstat for the TS-480 appears to be broken. The TS-480 has two power off modes, one (PS3;) where the cpu sleeps and the other (PS0;) where the cpu is active. Shouldn't the TS-480 attempt power on as part of the init?

Log below.

Thanks!

--Howard W6HN

pi@rigpi:
git
Report bugs to hamlib-developer@lists.sourceforge.net

rig_init called
initrigs4_kenwood called
rig_register called
rig_register: rig_register (2013)
rig_register called
rig_register: rig_register (2001)
rig_register called
rig_register: rig_register (2025)
rig_register called
rig_register: rig_register (2003)
rig_register called
rig_register: rig_register (2004)
rig_register called
rig_register: rig_register (2016)
rig_register called
rig_register: rig_register (2024)
rig_register called
rig_register: rig_register (2005)
rig_register called
rig_register: rig_register (2007)
rig_register called
rig_register: rig_register (2009)
rig_register called
rig_register: rig_register (2010)
rig_register called
rig_register: rig_register (2022)
rig_register called
rig_register: rig_register (2014)
rig_register called
rig_register: rig_register (2030)
rig_register called
rig_register: rig_register (2021)
rig_register called
rig_register: rig_register (2029)
rig_register called
rig_register: rig_register (2043)
rig_register called
rig_register: rig_register (2044)
rig_register called
rig_register: rig_register (2045)
rig_register called
rig_register: rig_register (2038)
rig_register called
rig_register: rig_register (2002)
rig_register called
rig_register: rig_register (2011)
rig_register called
rig_register: rig_register (2006)
rig_register called
rig_register: rig_register (2008)
rig_register called
rig_register: rig_register (2015)
rig_register called
rig_register: rig_register (2026)
rig_register called
rig_register: rig_register (2017)
rig_register called
rig_register: rig_register (2033)
rig_register called
rig_register: rig_register (2042)
rig_register called
rig_register: rig_register (2020)
rig_register called
rig_register: rig_register (2023)
rig_register called
rig_register: rig_register (2027)
rig_register called
rig_register: rig_register (2034)
rig_register called
rig_register: rig_register (2031)
rig_register called
rig_register: rig_register (2039)
rig_register called
rig_register: rig_register (2037)
rig_register called
rig_register: rig_register (2028)
rig_register called
rig_register: rig_register (2019)
rig_register called
rig_register: rig_register (2032)
rig_register called
rig_register: rig_register (2036)
rig_register called
rig_register: rig_register (2040)
rig_register called
rig_register: rig_register (2041)
kenwood_init called, version 1.5
kenwood_init: if_len = 37
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
serial_flush: tcflush
rig_get_vfo called
kenwood_get_vfo_if called
kenwood_get_if called
kenwood_safe_transaction called
kenwood_transaction called
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): RX 1 characters
0000 00 .
kenwood_transaction: wrong reply for command IF
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200264 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200261 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200257 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200256 seconds after 0 chars
kenwood_transaction: cmdstr = IF
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 3 bytes
0000 49 46 3b IF;
read_string called
read_string(): Timed out 0.200258 seconds after 0 chars
rig_set_parm called
Opened rig model 2028, 'TS-480'
Backend version: 1.5.5, Status: Untested

Rig command: \set_powerstat 1
rigctl_parse: debug1
rigctl_parse: debug3
rigctl_parse: debug4
rigctl_parse: debug5
rigctl_parse: debug10
rig_set_powerstat called
kenwood_transaction called
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): RX 1 characters
0000 00 .
kenwood_transaction: wrong reply for command verification ID
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200267 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200263 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200265 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200268 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200266 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200271 seconds after 0 chars
kenwood_transaction: cmdstr = PS1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 4 bytes
0000 50 53 31 3b PS1;
write_block called
write_block(): TX 3 bytes
0000 49 44 3b ID;
read_string called
read_string(): Timed out 0.200274 seconds after 0 chars
kenwood_set_powerstat called status=1
kenwood_set_powerstat: timeout waiting for powerup, try 1
set_powerstat: error = Communication timed out

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by hlnurse** [comment]
No, w ;;;;PS1; does not wake it up.

Rig command: w ;;;;PS1;
rigctl_parse: debug1
rigctl_parse: debug2
rigctl_parse: debug2a
rigctl_parse: debug5
rigctl_parse: debug10
rigctl_send_cmd: called
rigctl_send_cmd: backend_num=2
rigctl_send_cmd: KENWOOD
rigctl_send_cmd: arg1=;;;;PS1;
rigctl_send_cmd: bufcmd=;;;;PS1;
rigctl_send_cmd: text protocol, send_cmd_term=0x00 0x0d 0x00
serial_flush called
serial_flush: tcflush
rigctl_send_cmd: rigport=3, bufcmd=;;;;PS1;, cmd_len=8
write_block called
write_block(): TX 8 bytes
0000    3b 3b 3b 3b 50 53 31 3b                             ;;;;PS1;        
rigctl_send_cmd: debug Cmd
read_string called
read_string(): RX 1 characters
0000    00                                                  .               
Reply:

**Comment by hlnurse** [comment]
No improvement with the new fork in \set_powerstat, init or w command. Debug logs look the same.

--Howard

**Comment by mdblack98** [comment]
You said your manual shows PS3 ?  Can you send me your CAT manual?
The one I have gave the ";;;;PS1;" to wake up but I guess the manual is wrong or your rig doesn't behave as the manual says it should.
So unless your manual has some other way to take up the rig I don't know what else to do.
The debug logs should not look quite the same since it's sending the new ;;;;PS1 command now several times.  I'm concerned though that it might cause a timeout in WSJT-X or such. 
Mike

 

    On Tuesday, March 3, 2020, 05:51:52 PM CST, hlnurse <notifications@github.com> wrote:  
 
 
No improvement with the new fork in \set_powerstat, init or w command. Debug logs look the same.

--Howard

**Comment by mdblack98** [comment]
Try my for again please...I had a typo in there....
Mike

 

    On Tuesday, March 3, 2020, 05:30:28 PM CST, hlnurse <notifications@github.com> wrote:  
 
 
No, w ;;;;PS1; does not wake it up.

Rig command: w ;;;;PS1;
rigctl_parse: debug1
rigctl_parse: debug2
rigctl_parse: debug2a
rigctl_parse: debug5
rigctl_parse: debug10
rigctl_send_cmd: called
rigctl_send_cmd: backend_num=2
rigctl_send_cmd: KENWOOD
rigctl_send_cmd: arg1=;;;;PS1;
rigctl_send_cmd: bufcmd=;;;;PS1;
rigctl_send_cmd: text protocol, send_cmd_term=0x00 0x0d 0x00
serial_flush called
serial_flush: tcflush
rigctl_send_cmd: rigport=3, bufcmd=;;;;PS1;, cmd_len=8
write_block called
write_block(): TX 8 bytes
0000 3b 3b 3b 3b 50 53 31 3b ;;;;PS1;
rigctl_send_cmd: debug Cmd
read_string called
read_string(): RX 1 characters
0000 00 .
Reply:

**Comment by hlnurse** [comment]
Hi Mike,

I was wrong about PS3;, you are correct that PS9; is used for the CPU sleep mode. I will test again in a bit with the new fork.  I’m thinking that the only way PS1; works is if you turn off the radio by PS0; or PS9;, not by means of the power switch.  I’m testing using a radio owned by a club at a location remote to the members, so it may take time to confirm my suspicion.  (I see nothing about this in the manual.)

—Howard

**Comment by hlnurse** [comment]
Good news, in the latest fork the power on/off works perfectly with the TS-480.

Thank you!

Howard W6HN

**Comment by mdblack98** [comment]
Fixed
