### ISSUE TITLE
Icom IC-7300 power-on during init

### ISSUE THREAD

**Issue by hlnurse** [Hamlib/Hamlib#208]
Starting with power off, IC-7300, rigctld successfully powers up the radio but terminates with a "Feature not available" error. It also appears that power on is not being sent (although debug says it is) before the long string fe attempt.

Log below.

--Howard

---------------------------------------------------
pi@rigpi4:~ $ rigctld -m 3073 -r /dev/ttyUSB0 -s 115200 -vvvvv
Recommend using --vfo switch for rigctld
rigctl and netrigctl will automatically detect vfo mode
rigctld, Hamlib 4.0~git
Report bugs to <hamlib-developer@lists.sourceforge.net>

rig_init called
initrigs4_icom: _init called
rig_register called
rig_register: rig_register (3055)
rig_register called
rig_register: rig_register (3009)
rig_register called
rig_register: rig_register (3010)
rig_register called
rig_register: rig_register (3011)
rig_register called
rig_register: rig_register (3013)
rig_register called
rig_register: rig_register (3014)
rig_register called
rig_register: rig_register (3015)
rig_register called
rig_register: rig_register (3019)
rig_register called
rig_register: rig_register (3020)
rig_register called
rig_register: rig_register (3021)
rig_register called
rig_register: rig_register (3022)
rig_register called
rig_register: rig_register (3067)
rig_register called
rig_register: rig_register (3023)
rig_register called
rig_register: rig_register (3046)
rig_register called
rig_register: rig_register (3024)
rig_register called
rig_register: rig_register (3028)
rig_register called
rig_register: rig_register (3030)
rig_register called
rig_register: rig_register (3026)
rig_register called
rig_register: rig_register (3027)
rig_register called
rig_register: rig_register (3047)
rig_register called
rig_register: rig_register (3057)
rig_register called
rig_register: rig_register (3063)
rig_register called
rig_register: rig_register (3029)
rig_register called
rig_register: rig_register (3062)
rig_register called
rig_register: rig_register (3045)
rig_register called
rig_register: rig_register (3056)
rig_register called
rig_register: rig_register (3075)
rig_register called
rig_register: rig_register (3060)
rig_register called
rig_register: rig_register (3070)
rig_register called
rig_register: rig_register (3061)
rig_register called
rig_register: rig_register (3073)
rig_register called
rig_register: rig_register (3078)
rig_register called
rig_register: rig_register (3031)
rig_register called
rig_register: rig_register (3012)
rig_register called
rig_register: rig_register (3016)
rig_register called
rig_register: rig_register (3032)
rig_register called
rig_register: rig_register (3034)
rig_register called
rig_register: rig_register (3044)
rig_register called
rig_register: rig_register (3068)
rig_register called
rig_register: rig_register (3035)
rig_register called
rig_register: rig_register (3081)
rig_register called
rig_register: rig_register (3069)
rig_register called
rig_register: rig_register (3077)
rig_register called
rig_register: rig_register (3036)
rig_register called
rig_register: rig_register (3058)
rig_register called
rig_register: rig_register (3080)
rig_register called
rig_register: rig_register (3037)
rig_register called
rig_register: rig_register (3038)
rig_register called
rig_register: rig_register (3039)
rig_register called
rig_register: rig_register (3040)
rig_register called
rig_register: rig_register (3041)
rig_register called
rig_register: rig_register (3042)
rig_register called
rig_register: rig_register (3079)
rig_register called
rig_register: rig_register (3043)
rig_register called
rig_register: rig_register (3066)
rig_register called
rig_register: rig_register (3003)
rig_register called
rig_register: rig_register (3004)
rig_register called
rig_register: rig_register (3006)
rig_register called
rig_register: rig_register (3007)
rig_register called
rig_register: rig_register (3002)
rig_register called
rig_register: rig_register (3052)
rig_register called
rig_register: rig_register (3053)
rig_register called
rig_register: rig_register (3051)
rig_register called
rig_register: rig_register (3064)
rig_register called
rig_register: rig_register (3065)
rig_register called
rig_register: rig_register (3054)
rig_register called
rig_register: rig_register (3083)
rig_register called
rig_register: rig_register (3084)
rig_register called
rig_register: rig_register (3082)
rig_register called
rig_register: rig_register (3071)
rig_register called
rig_register: rig_register (3072)
rig_register called
rig_register: rig_register (3074)
rig_register called
rig_register: rig_register (3076)
icom_init called
icom_init: done
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
serial_flush: tcflush
icom_rig_open 728 
icom_rig_open: IC-7300 v0.32.5
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): Timed out 1.1031 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): Timed out 1.1051 seconds after 0 chars
icom_transaction: failed: Unknown error -13
icom_get_usb_echo_off 697 
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000    fe fe 94 e0 19 00 fd                                .......         
read_string called
read_string(): Timed out 1.1053 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000    fe fe 94 e0 19 00 fd                                .......         
read_string called
read_string(): Timed out 1.1031 seconds after 0 chars
icom_transaction: failed: Unknown error -5
icom_rig_open trying power on
rig_set_powerstat called
icom_set_powerstat called status=1
icom_set_powerstat: PWR_ON failed, trying 0xfe's
write_block called
write_block(): TX 175 bytes
0000    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0010    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0020    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0030    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0040    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0050    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0060    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0070    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0080    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
0090    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe     ................
00a0    fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe        ............... 
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000    fe fe 94 e0 18 01 fd                                .......         
read_string called
read_string(): RX 5 characters
0000    fe e0 18 01 fd                                      .....           
icom_transaction: failed: Unknown error -8
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): Timed out 1.1029 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): Timed out 1.1037 seconds after 0 chars
icom_transaction: failed: Unknown error -13
icom_get_usb_echo_off 697 
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000    fe fe 94 e0 19 00 fd                                .......         
read_string called
read_string(): RX 7 characters
0000    fe fe 94 e0 19 00 fd                                .......         
read_string called
read_string(): RX 8 characters
0000    fe fe e0 94 19 00 94 fd                             ........        
icom_get_usb_echo_off: USB echo off detected
rig_get_freq called
icom_get_freq called for currVFO
set_vfo_curr: vfo=currVFO, curr_vfo=
set_vfo_curr: Asking for currVFO,  currVFO=
set_vfo_curr: curr_vfo now=
icom_get_freq: VFO_RX requested, vfo=currVFO
icom_get_freq: using vfo=VFOA
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): RX 6 characters
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): RX 11 characters
0000    fe fe e0 94 03 00 40 27 14 00 fd                    ......@'...     
from_bcd called
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): RX 6 characters
0000    fe fe 94 e0 03 fd                                   ......          
read_string called
read_string(): RX 11 characters
0000    fe fe e0 94 03 00 40 27 14 00 fd                    ......@'...     
icom_get_usb_echo_off: USB echo on detected
rig_get_func called
rig_has_get_func called
icom_rig_open: satmode=0
rig_open: error = Feature not available 
pi@rigpi4:

**Comment by mdblack98** [comment]
Fixed

**Comment by N0NB** [comment]
Just fixed it Howard.
de Mike W9MDB

 

    On Saturday, March 7, 2020, 06:32:39 PM CST, hlnurse <notifications@github.com> wrote:  
 
 
Starting with power off, IC-7300, rigctld successfully powers up the radio but terminates with a "Feature not available" error. It also appears that power on is not being sent (although debug says it is) before the log string fe attempt.

Log below.

--Howard

pi@rigpi4:~ $ rigctld -m 3073 -r /dev/ttyUSB0 -s 115200 -vvvvv
Recommend using --vfo switch for rigctld
rigctl and netrigctl will automatically detect vfo mode
rigctld, Hamlib 4.0~git
Report bugs to hamlib-developer@lists.sourceforge.net

rig_init called
initrigs4_icom: _init called
rig_register called
rig_register: rig_register (3055)
rig_register called
rig_register: rig_register (3009)
rig_register called
rig_register: rig_register (3010)
rig_register called
rig_register: rig_register (3011)
rig_register called
rig_register: rig_register (3013)
rig_register called
rig_register: rig_register (3014)
rig_register called
rig_register: rig_register (3015)
rig_register called
rig_register: rig_register (3019)
rig_register called
rig_register: rig_register (3020)
rig_register called
rig_register: rig_register (3021)
rig_register called
rig_register: rig_register (3022)
rig_register called
rig_register: rig_register (3067)
rig_register called
rig_register: rig_register (3023)
rig_register called
rig_register: rig_register (3046)
rig_register called
rig_register: rig_register (3024)
rig_register called
rig_register: rig_register (3028)
rig_register called
rig_register: rig_register (3030)
rig_register called
rig_register: rig_register (3026)
rig_register called
rig_register: rig_register (3027)
rig_register called
rig_register: rig_register (3047)
rig_register called
rig_register: rig_register (3057)
rig_register called
rig_register: rig_register (3063)
rig_register called
rig_register: rig_register (3029)
rig_register called
rig_register: rig_register (3062)
rig_register called
rig_register: rig_register (3045)
rig_register called
rig_register: rig_register (3056)
rig_register called
rig_register: rig_register (3075)
rig_register called
rig_register: rig_register (3060)
rig_register called
rig_register: rig_register (3070)
rig_register called
rig_register: rig_register (3061)
rig_register called
rig_register: rig_register (3073)
rig_register called
rig_register: rig_register (3078)
rig_register called
rig_register: rig_register (3031)
rig_register called
rig_register: rig_register (3012)
rig_register called
rig_register: rig_register (3016)
rig_register called
rig_register: rig_register (3032)
rig_register called
rig_register: rig_register (3034)
rig_register called
rig_register: rig_register (3044)
rig_register called
rig_register: rig_register (3068)
rig_register called
rig_register: rig_register (3035)
rig_register called
rig_register: rig_register (3081)
rig_register called
rig_register: rig_register (3069)
rig_register called
rig_register: rig_register (3077)
rig_register called
rig_register: rig_register (3036)
rig_register called
rig_register: rig_register (3058)
rig_register called
rig_register: rig_register (3080)
rig_register called
rig_register: rig_register (3037)
rig_register called
rig_register: rig_register (3038)
rig_register called
rig_register: rig_register (3039)
rig_register called
rig_register: rig_register (3040)
rig_register called
rig_register: rig_register (3041)
rig_register called
rig_register: rig_register (3042)
rig_register called
rig_register: rig_register (3079)
rig_register called
rig_register: rig_register (3043)
rig_register called
rig_register: rig_register (3066)
rig_register called
rig_register: rig_register (3003)
rig_register called
rig_register: rig_register (3004)
rig_register called
rig_register: rig_register (3006)
rig_register called
rig_register: rig_register (3007)
rig_register called
rig_register: rig_register (3002)
rig_register called
rig_register: rig_register (3052)
rig_register called
rig_register: rig_register (3053)
rig_register called
rig_register: rig_register (3051)
rig_register called
rig_register: rig_register (3064)
rig_register called
rig_register: rig_register (3065)
rig_register called
rig_register: rig_register (3054)
rig_register called
rig_register: rig_register (3083)
rig_register called
rig_register: rig_register (3084)
rig_register called
rig_register: rig_register (3082)
rig_register called
rig_register: rig_register (3071)
rig_register called
rig_register: rig_register (3072)
rig_register called
rig_register: rig_register (3074)
rig_register called
rig_register: rig_register (3076)
icom_init called
icom_init: done
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
serial_flush: tcflush
icom_rig_open 728
icom_rig_open: IC-7300 v0.32.5
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): Timed out 1.1031 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): Timed out 1.1051 seconds after 0 chars
icom_transaction: failed: Unknown error -13
icom_get_usb_echo_off 697
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000 fe fe 94 e0 19 00 fd .......
read_string called
read_string(): Timed out 1.1053 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000 fe fe 94 e0 19 00 fd .......
read_string called
read_string(): Timed out 1.1031 seconds after 0 chars
icom_transaction: failed: Unknown error -5
icom_rig_open trying power on
rig_set_powerstat called
icom_set_powerstat called status=1
icom_set_powerstat: PWR_ON failed, trying 0xfe's
write_block called
write_block(): TX 175 bytes
0000 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0010 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0020 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0030 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0040 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0050 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0060 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0070 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0080 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
0090 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ................
00a0 fe fe fe fe fe fe fe fe fe fe fe fe fe fe fe ...............
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000 fe fe 94 e0 18 01 fd .......
read_string called
read_string(): RX 5 characters
0000 fe e0 18 01 fd .....
icom_transaction: failed: Unknown error -8
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): Timed out 1.1029 seconds after 0 chars
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): Timed out 1.1037 seconds after 0 chars
icom_transaction: failed: Unknown error -13
icom_get_usb_echo_off 697
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 7 bytes
0000 fe fe 94 e0 19 00 fd .......
read_string called
read_string(): RX 7 characters
0000 fe fe 94 e0 19 00 fd .......
read_string called
read_string(): RX 8 characters
0000 fe fe e0 94 19 00 94 fd ........
icom_get_usb_echo_off: USB echo off detected
rig_get_freq called
icom_get_freq called for currVFO
set_vfo_curr: vfo=currVFO, curr_vfo=
set_vfo_curr: Asking for currVFO, currVFO=
set_vfo_curr: curr_vfo now=
icom_get_freq: VFO_RX requested, vfo=currVFO
icom_get_freq: using vfo=VFOA
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): RX 6 characters
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): RX 11 characters
0000 fe fe e0 94 03 00 40 27 14 00 fd ......@'...
from_bcd called
icom_get_usb_echo_off called
icom_get_usb_echo_off: retry temp set to 1
serial_flush called
serial_flush: tcflush
write_block called
write_block(): TX 6 bytes
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): RX 6 characters
0000 fe fe 94 e0 03 fd ......
read_string called
read_string(): RX 11 characters
0000 fe fe e0 94 03 00 40 27 14 00 fd ......@'...
icom_get_usb_echo_off: USB echo on detected
rig_get_func called
rig_has_get_func called
icom_rig_open: satmode=0
rig_open: error = Feature not available
pi@rigpi4:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer
