### ISSUE TITLE
Github test

### ISSUE THREAD

**Issue by mdblack98** [Hamlib/Hamlib#211]
Testing github email notifications for their debugging....
This is the posting of an issue
de Mike W9MDB

**Comment by N0NB** [comment]
Testing replies on github....

 

    On Monday, March 30, 2020, 08:19:11 AM CDT, Michael Black <notifications@github.com> wrote:  
 
 


Testing github email notifications for their debugging....
This is the posting of an issue
de Mike W9MDB

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
_______________________________________________
Hamlib-developer mailing list
Hamlib-developer@lists.sourceforge.net
https://lists.sourceforge.net/lists/listinfo/hamlib-developer

**Comment by mdblack98** [comment]
Test#2 reply
