### ISSUE TITLE
pytest.py reports 'rig_state' object has no attribute 'itu_region'

### ISSUE THREAD

**Issue by N0NB** [Hamlib/Hamlib#375]
```
$ bindings/pytest.py 
bindings/pytest.py: Python 2.7.16; Hamlib 4.0~rc2

status(str):		Command completed successfully
get_conf:		path = /dev/Rig, retry = 5, ITU region = 
freq:			5700000000.0
mode:			FM 
bandwidth:		15000
mode:			CW 
bandwidth:		15000
ITU_region:		Traceback (most recent call last):
  File "bindings/pytest.py", line 126, in <module>
    StartUp([0,1]["-v" in sys.argv])
  File "bindings/pytest.py", line 53, in StartUp
    print "ITU_region:\t\t", my_rig.state.itu_region
  File "/home/nate/local/lib/python2.7/site-packages/Hamlib.py", line 2624, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, rig_state, name)
  File "/home/nate/local/lib/python2.7/site-packages/Hamlib.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'rig_state' object has no attribute 'itu_region'
```

It has been quite some time since I tested this so I'm not sure when this crept in.

**Comment by mdblack98** [comment]
I updated them...I don't build the bindings either...surprised some others hadn't seen this though.
That whole itu_region thing is changing.  Rigs aren't being manufactured that way anymore and it wasn't being used.They (Icom) are going by country now prompted by the IC-9700.
There's a new field that was added to describe what the freq range refers to that can be tagged ITU1 or such if appropriate.
You'll see this kind of stuff now    .rx_range_list2 =   { // EUR Version -- Europe        {MHz(144), MHz(146), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "EUR"},        {MHz(430), MHz(440), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "EUR"},        {MHz(1240), MHz(1300), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "EUR"},        RIG_FRNG_END,    },    .rx_range_list1 =   { // USA Version -- United States        {MHz(144), MHz(148), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "USA"},        {MHz(430), MHz(450), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "USA"},        {MHz(1240), MHz(1300), IC9700_ALL_RX_MODES, -1, -1, IC9700_VFOS, RIG_ANT_CURR, "USA"},        RIG_FRNG_END,    },



commit 31115b6a161fe147f8f70e6528051aaf1d82e6cbAuthor: Michael Black W9MDB <mdblack98@yahoo.com>Date:   Fri Jul 24 14:23:38 2020 -0500
    deprecate itu_region
commit 119f5e6eb98902177cbfdd5db9967cb1c309a644Author: Michael Black W9MDB <mdblack98@yahoo.com>Date:   Fri Jul 24 12:57:33 2020 -0500
    Remove itu_region from rigctl_paparse.c and replace with constant 0 -- it's not used at all by any rig



 

    On Saturday, September 12, 2020, 08:43:43 AM CDT, Nate Bargmann <notifications@github.com> wrote:  
 
 

$ bindings/pytest.py 
bindings/pytest.py: Python 2.7.16; Hamlib 4.0~rc2

status(str):		Command completed successfully
get_conf:		path = /dev/Rig, retry = 5, ITU region = 
freq:			5700000000.0
mode:			FM 
bandwidth:		15000
mode:			CW 
bandwidth:		15000
ITU_region:		Traceback (most recent call last):
  File "bindings/pytest.py", line 126, in <module>
    StartUp([0,1]["-v" in sys.argv])
  File "bindings/pytest.py", line 53, in StartUp
    print "ITU_region:\t\t", my_rig.state.itu_region
  File "/home/nate/local/lib/python2.7/site-packages/Hamlib.py", line 2624, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, rig_state, name)
  File "/home/nate/local/lib/python2.7/site-packages/Hamlib.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'rig_state' object has no attribute 'itu_region'

It has been quite some time since I tested this so I'm not sure when this crept in.
