### ISSUE TITLE
IC7000 --vfo mode Problem switching to VFOB

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#427]
IC7000   
VFO switching was fine with rigctld when not using --vfo mode

In --vfo mode

If I switch to VFOB with piWebCAT I then get fast oscillatory switching
between VFOs
- assumed reason: There are ongoing repetitive reads of various parameters 
  which are use  VFOA as dummy parameter in the command.

and every read flips to VFOA and back to VFOB

Investigating:

With VFOA selected
    U VFOA NR 1    works fine
    U VFOB NR 1 flips the rig to VFOB and then immediately back to VFOA

With VFOB selected
  U VFOB NR 1 works fine
  U VFOA NR 1 flips the rig to VFOA and then immediately back to VFOB

More importantly, my piWebCAT software is doing repetitve synchonising reads
for selected on-screen controls. eg: u VFOA NR

On testing this at the command line with VFOB selected:
  u VFOA NR flips the VFO selection to VFOA and then immediately back to VFOB (reads NR correctly)
I think it is the stream of repetitive such reads that is causing the oscillating behaviour.

I am in --vfo mode so I have to use VFOA as a dummy parameter 

I think its ok if I use  u VFOB NR  with VFOB selected.  - but \get_vfo is not supported

Ian
G3VPX
Problem in --vfo  mode with piWebCAT:

Question:  Should I not be using --vfo mode with this rig?
.... inwhcih case I need to install a --vfo configuration option ....
not a problem.

**Comment by mdblack98** [comment]
Commands like NR are not VFO-addressable in most rigs.  So in order to read the opposite VFO the VFO will get switched, the read occurs, then it will switch back to the default VFO.  Any read needs to not mess with the default VFO.
The best thing for you to do is select VFOA  and do all the VFOA reads, then switch to VFOB and do all the VFOB reads, then switch back to VFOA if that was the starting VFO.  But you can't query Icom rigs for the active VFO so you have to force it yourself.  I've thought about returning the "virtual" VFO but don't like that idea.  Better to force what your app wants as the default as users may be twiddling the rig.
