### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by Ian-G3VPX** [Hamlib/Hamlib#803]
I downloaded the latest Hamlib-master.zip yesterday   - failed on make.
Rebuilt from 13th Aug version - ok

I downloaded the latest Hamlib-master.zip today   - failed on make.
Rebuilt from 13th Aug version - ok
see attached screen dump

Ian G3VPX

![2021-09-20_17-00-18](https://user-images.githubusercontent.com/72380690/134036233-5b3d732d-083c-49a6-b999-50f4642fc0a2.jpg)

**Comment by mdblack98** [comment]
Could you replace the top include section in rigtestlibusb.c with this and tell me if it works?
#include <stdio.h>#include <string.h>
#if defined(HAVE_LIBUSB_H)
#include "libusb.h"
#else
#include <libusb-1.0/libusb.h>
#endif

Mike W9MDB


 

    On Monday, September 20, 2021, 11:11:54 AM CDT, Ian-G3VPX ***@***.***> wrote:  
 
 


I downloaded the latest Hamlib-master.zip yesterday - failed on make.
Rebuilt from 13th Aug version - ok

I downloaded the latest Hamlib-master.zip today - failed on make.
Rebuilt from 13th Aug version - ok
see attached screen dump

Ian G3VPX



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ian-G3VPX** [comment]
Hi Mike
Where is rigtestlibusb.c ???
I've searched all the folders in Hamlib-master (apart from the 
individual rotator fodlers)
and I can't find it
Ian
G3VPX

**Comment by wutje** [comment]
In the tests folder?

**Comment by Ian-G3VPX** [comment]
..
#include <stdio.h>#include <string.h>  threw an error

So   Using:
#include <stdio.h>
#include <string.h>
#if defined(HAVE_LIBUSB_H)
#include "libusb.h"
#else
#include <libusb-1.0/libusb.h>
#endif

I get the attached error message:
![liusb_error](https://user-images.githubusercontent.com/72380690/134074066-445c6f7a-0cbe-4a10-bc0d-47d99506907b.jpg)

Ian
G3VPX

**Comment by mdblack98** [comment]
I need to see your config.log and include/config.hPlease attach.

 

    On Monday, September 20, 2021, 03:53:27 PM CDT, Ian-G3VPX ***@***.***> wrote:  
 
 


..
#include <stdio.h>#include <string.h> threw an error

So Using:
#include <stdio.h>
#include <string.h>
#if defined(HAVE_LIBUSB_H)
#include "libusb.h"
#else
#include <libusb-1.0/libusb.h>
#endif

I get the attached error message:


Ian
G3VPX

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ian-G3VPX** [comment]
config.h and config.log attached

[config.log](https://github.com/Hamlib/Hamlib/files/7198980/config.log)

[config.h.txt](https://github.com/Hamlib/Hamlib/files/7198983/config.h.txt)

Ian 
G3VPX
