### ISSUE TITLE
Yaesu newcat if shift

### ISSUE THREAD

**Issue by Johnny-Sierra** [Hamlib/Hamlib#879]
Enhancement:
Add if shift capability in Yaesu newcat backend (command IS).

**Comment by mdblack98** [comment]
We don't have an API for this....do you have a proposal?

**Comment by Johnny-Sierra** [comment]
The if-shift is a common feature, so I suggest to create a new RIG_LEVEL constant and use the existing rig_set_level rig_get_level functions.

For Yaesu (newcat) the command prototype is:

Set IS P1 +/- P2 P2 P2 P2 ;
Read IS P1 ;
Answer IS P1 +/- P2 P2 P2 P2 ;

where P1 = 0,
P2 = -1200 to +1200 (20 Hz steps)

**Comment by mdblack98** [comment]
LEVEL_IF is already implemented.
I just updated the rig.h to make it a little clearer
Mike W9MDB

 

    On Friday, December 3, 2021, 12:45:22 PM CST, Johnny-Sierra ***@***.***> wrote:  
 
 


The if-shift is a common feature, so I suggest to create a new RIG_LEVEL constant and use the existing rig_set_level rig_get_level functions.

For Yaesu (newcat) the command prototype is:

Set IS P1 +/- P2 P2 P2 P2 ;
Read IS P1 ;
Answer IS P1 +/- P2 P2 P2 P2 ;

where P1 = 0,
P2 = -1200 to +1200 (20 Hz steps)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnny-Sierra** [comment]
Very well, I missed it. HI
And also already implemented in the Yaesu newcat API.

Yes it isn't clear, from wiki:
<html><body>
<h2 class="memtitle">RIG_LEVEL_IF</h2>

<div class="memitem">
<div class="memproto">
      

#define RIG_LEVEL_IF   CONSTANT_64BIT_FLAG(6)
--



</div><div class="memdoc">
<p><code>IF</code> – IF, arg int (Hz) </p>

</div>
</div>
</body>
</html>
