### ISSUE TITLE
Add agc_level_e from value and string conversion

### ISSUE THREAD

**Issue by Johnny-Sierra** [Hamlib/Hamlib#883]
In addition to internal API rig_stragclevel please add the following:

```
agc_level_e levelagcvalue (int agcValue)
{
    agc_level_e agcLevel;
    switch (agcValue)
    {
    case 0: agcLevel = RIG_AGC_OFF; break;
    case 1: agcLevel = RIG_AGC_SUPERFAST; break;
    case 2: agcLevel = RIG_AGC_FAST; break;
    case 3: agcLevel = RIG_AGC_SLOW; break;
    case 4: agcLevel = RIG_AGC_USER; break;
    case 5: agcLevel = RIG_AGC_MEDIUM; break;
    case 6: agcLevel = RIG_AGC_AUTO; break;
    default: agcLevel = RIG_AGC_AUTO; break;
    }
    return agcLevel;
}

agc_level_e levelagcstr (string agcString)
{
    agc_level_e agcLevel;
    if (agcString == "OFF") agcLevel = RIG_AGC_OFF;
    else if (agcString == "SUPERFAST") agcLevel = RIG_AGC_SUPERFAST;
    else if (agcString == "FAST") agcLevel = RIG_AGC_FAST;
    else if (agcString == "SLOW") agcLevel = RIG_AGC_SLOW;
    else if (agcString == "USER") agcLevel = RIG_AGC_USER;
    else if (agcString == "MEDIUM") agcLevel = RIG_AGC_MEDIUM;
    else agcLevel = RIG_AGC_AUTO;
    return agcLevel;
}
```

**Comment by mdblack98** [comment]
Do you have a pull request you want to submit?
Are these going to be used somewhere?  I assume in rigctl?
Mike W9MDB

 

    On Tuesday, December 7, 2021, 03:44:52 PM CST, Johnny-Sierra ***@***.***> wrote:  
 
 


In addition to internal API rig_stragclevel please add the following:
agc_level_e levelagcvalue (int agcValue)
{
    agc_level_e agcLevel;
    switch (agcValue)
    {
    case 0: agcLevel = RIG_AGC_OFF; break;
    case 1: agcLevel = RIG_AGC_SUPERFAST; break;
    case 2: agcLevel = RIG_AGC_FAST; break;
    case 3: agcLevel = RIG_AGC_SLOW; break;
    case 4: agcLevel = RIG_AGC_USER; break;
    case 5: agcLevel = RIG_AGC_MEDIUM; break;
    case 6: agcLevel = RIG_AGC_AUTO; break;
    default: agcLevel = RIG_AGC_AUTO; break;
    }
    return agcLevel;
}

agc_level_e levelagcstr (string agcString)
{
    agc_level_e agcLevel;
    if (agcString == "OFF") agcLevel = RIG_AGC_OFF;
    else if (agcString == "SUPERFAST") agcLevel = RIG_AGC_SUPERFAST;
    else if (agcString == "FAST") agcLevel = RIG_AGC_FAST;
    else if (agcString == "SLOW") agcLevel = RIG_AGC_SLOW;
    else if (agcString == "USER") agcLevel = RIG_AGC_USER;
    else if (agcString == "MEDIUM") agcLevel = RIG_AGC_MEDIUM;
    else agcLevel = RIG_AGC_AUTO;
    return agcLevel;
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnny-Sierra** [comment]
Sorry, I'm not yet skilled with GitHub, so I don't know how to pull a request.

Please, if you agree and think that my proposal could be useful, you can add it into **misc.c** where are _rig_stragclevel_ and other utilities.
Sorry, some makeup are required, for example rename them with suffux _rig__ and convert string to maybe char *

TNX

**Comment by mdblack98** [comment]
But where are they referred to?
What function is calling them?
Mike W9MDB

 

    On Tuesday, December 7, 2021, 04:31:23 PM CST, Johnny-Sierra ***@***.***> wrote:  
 
 


Sorry, I'm not yet skilled with GitHub, so I don't know how to pull a request.

Please, if you agree and think that my proposal could be useful, you can add it into misc.c where are rig_stragclevel and other utilities.
Sorry, some makeup are required, for example rename them with suffux rig_ and convert string to maybe char *

TNX

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnny-Sierra** [comment]
No Mike, they are utilities for the hamlib users, but not referred from other function of the library.

**Comment by mdblack98** [comment]
So you mean you want them exposed for the API and the shared library?

 

    On Wednesday, December 8, 2021, 12:32:27 PM CST, Johnny-Sierra ***@***.***> wrote:  
 
 


No Mike, they are utilities for the hamlib users, but not referred from other function of the library.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnny-Sierra** [comment]
I suppose that internal API are already exposed to external use and intended as utility http://hamlib.sourceforge.net/manuals/4.3/group__rig__internal.html
Infact I'm using some of them in my GUI, for example rig_strmode, rig_strmodes, rig_stragclevel, etc.
But if it is not the case, please discard my proposal.

**Comment by Johnny-Sierra** [comment]
Thanks.

I have another function, if you want to add it

```
value_t rig_valueagclevel (agc_level_e agcLevel)
{
    value_t value;

    if (agcLevel == RIG_AGC_OFF) value.i = 0;
    else if (agcLevel == RIG_AGC_SUPERFAST) value.i = 1;
    else if (agcLevel == RIG_AGC_FAST) value.i = 2;
    else if (agcLevel == RIG_AGC_SLOW) value.i = 3;
    else if (agcLevel == RIG_AGC_USER) value.i = 4;
    else if (agcLevel == RIG_AGC_MEDIUM) value.i = 5;
    else value.i = 6; //RIG_AGC_AUTO

    return value;
}

```
