### ISSUE TITLE
Not able to use Sub without split mode ICOM.

### ISSUE THREAD

**Issue by cantudo** [Hamlib/Hamlib#889]
https://github.com/Hamlib/Hamlib/blob/b78ec43e2e8c391f0eca5761f7d059c013b23173/rigs/icom/icom.c#L2673-L2684

Hello, I have an ICOM 9100. I wanted to change to Sub using Hamlib, and I noticed that you can only change to Sub (refer to code above) if you have Split mode enabled, otherwise it forces you to use VFOB, i get that you can just use VFOB if you are not doing split mode, but why force the user?

Thank you.

**Comment by mdblack98** [comment]
Try using SUB_A and SUB_B for direct access.
Mike W9MDB

 

    On Sunday, December 19, 2021, 11:41:53 AM CST, cantudo ***@***.***> wrote:  
 
 


https://github.com/Hamlib/Hamlib/blob/b78ec43e2e8c391f0eca5761f7d059c013b23173/rigs/icom/icom.c#L2673-L2684

Hello, I have an ICOM 9100. I wanted to change to Sub using Hamlib, and I noticed that you can only change to Sub (refer to code above) if you have Split mode enabled, otherwise it forces you to use VFOB, i get that you can just use VFOB if you are not doing split mode, but why force the user?

Thank you.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cantudo** [comment]
Thank you very much, I can change without split mode enabled now using "V MainA" and "V SubA" in rigctl. :+1:

**Comment by cantudo** [comment]
@mdblack98 Should this be added to man page? It does not mention "MainA", "SubA", etc.
https://github.com/Hamlib/Hamlib/blob/b78ec43e2e8c391f0eca5761f7d059c013b23173/doc/man1/rigctld.1#L486-L487
